services:
  redis:
    image: "redis:alpine"
    command: [ "redis-server", "--requirepass", "${DOCKER_REDIS_PASSWORD}" ]
    #    ports:
    #      - "6380:6379"
    networks:
      - backend_net

  app:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SITE_REDIS_URI=redis://:${DOCKER_REDIS_PASSWORD}@redis:6379/0
      - REDIS_URI=redis://:${DOCKER_REDIS_PASSWORD}@redis:6379/1
      # Add your Auth0 variables here or in a .env file
    volumes:
      - ./:/home/node/app
    expose:
      - "3001"
    # Command to run your root package.json start script
    command: [ "npm", "start", "--prefix", "backend" ]
    depends_on:
      - redis
    networks:
      - backend_net

  proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [ app ]
    networks:
      - backend_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on: [ proxy ]
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
